### ISSUE TITLE
How to build all lua files into a single file?

### ISSUE THREAD

**Issue by lhing17** [scopterectus/Mok-HD#1]
How to build all lua files into a single file?

I saw that build.lua contains some configuration infomation. I don't know how to run the build process.

Thanks for your help.

**Comment by scopterectus** [comment]
> How to build all lua files into a single file?
> 
> I saw that build.lua contains some configuration infomation. I don't know how to run the build process.
> 
> Thanks for your help.

You should to use cheapack by nazarpunk. (https://github.com/nazarpunk/cheapack)

**Comment by lhing17** [comment]
Thanks.:)
